name: Test Platform App

on:
  push:
    branches:
      - main
    paths:
      - "platform/**"

defaults:
  run:
    working-directory: ./platform

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: cantguessthis
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip3 install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run application build
        run: ./build.sh

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "platform-xyz:latest"
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        usedocker: true
